Soru 1

In [50]:
notlar = [85, 92, 76, 92, 100, 76, 85, 92]

benzersiz = list(dict.fromkeys(notlar))
benzersiz.sort()

print("En düşük not: " , benzersiz[0] , ", En yüksek not: " , benzersiz[-1])

En düşük not:  76 , En yüksek not:  100


Soru 2

In [51]:
def Armstrong_num (sayi):
    toplam = 0

    for i in str(sayi):
        toplam = toplam + pow(int(i),3)

    if toplam == sayi:
        return True
    else:
        return False


num  = 153
num2 = 11

print(Armstrong_num(num))
print(Armstrong_num(num2))

True
False


Soru 3

In [52]:
A = {"Python", "R", "SQL", "Java"} 
B = {"C++", "Python", "JavaScript", "SQL"}

print(A & B)
print(A - B)
print(sorted(A | B))

{'Python', 'SQL'}
{'Java', 'R'}
['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


Soru 4

In [53]:
import random
import statistics

liste = []

for i in range(9):
    liste.append(int(random.random()*100))

print("Ortalama: " , statistics.mean(liste))
print("Standart Sapma: " , statistics.stdev(liste))

Ortalama:  45.888888888888886
Standart Sapma:  34.05673371172155


Soru 5

In [54]:
def kelime_sayaci(metin):
    kelime = metin.split(" ")

    print("Toplam kelime sayisi: " , len(kelime))
    print("En uzun kelime: " , max(kelime, key = len))
    print("En çok geçen kelime: " , statistics.mode(kelime))



kelime_sayaci("patates elma elma armut şeftali karpuz havuç salatalık armut elma")


Toplam kelime sayisi:  10
En uzun kelime:  salatalık
En çok geçen kelime:  elma


Soru 6

In [55]:
sayilar = [5, 12, 7, 18, 24, 3, 16]

filtre = list(filter(lambda num: num%2 == 0, sayilar))
kare =list(map(lambda num : num ** 2, sayilar))

print("Çiftler: " , filtre)
print("Kareleri: " , kare)
print("Sıralı: " , sorted(sayilar , reverse=True))

Çiftler:  [12, 18, 24, 16]
Kareleri:  [25, 144, 49, 324, 576, 9, 256]
Sıralı:  [24, 18, 16, 12, 7, 5, 3]


Soru 7

In [56]:
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]

sirali = sorted(kelimeler, key=lambda kelime: len(kelime))

print(sirali)

['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


Soru 8

In [57]:
karekter = "abc12def3"

def sayi_bulma(karekterler):
    char = ""

    for harf in karekterler:
        if harf.isnumeric():
            char += harf
        else:
            char += " "
    
    sayilar = char.split()
    toplam = 0

    for sayi in sayilar:
        toplam += int(sayi)
    
    print(toplam)

sayi_bulma(karekter)

15


Soru 9

In [58]:
import numpy as np

dizi = np.random.randint(0, 51, 10)
print("Dizi:", dizi)

ortalama = np.mean(dizi)

std = np.std(dizi)



Dizi: [22 48 16 46 11 15 30 39 13 38]


Soru 10

In [ ]:
matris = np.random.rand(5,5)
print("Asıl matris:\n" , matris)

sutun_ort = np.mean(matris,axis=0) 
print("\nSütun Ortalamaları:\n", sutun_ort)

yeni_matris = (matris > 0.5).astype(int)
print("\nBinary Matris:\n", yeni_matris)


Asıl matris:
 [[0.40987481 0.53063491 0.00292249 0.92576816 0.84542187]
 [0.25089715 0.34958935 0.70627644 0.1882807  0.88031629]
 [0.74020067 0.49418494 0.966964   0.32811263 0.75533293]
 [0.62473062 0.46632677 0.44652307 0.94253773 0.70708049]
 [0.1165574  0.98594375 0.88611702 0.9553852  0.36021656]]

Sütun Ortalamaları:
 [0.42845213 0.56533594 0.6017606  0.66801689 0.70967363]

Binary Matris:
 [[0 1 0 1 1]
 [0 0 1 0 1]
 [1 0 1 0 1]
 [1 0 0 1 1]
 [0 1 1 1 0]]
